json_payload_stuff = {"filterContext": {"selectedData":
                                      [{"filterId": "AbcFilter", "filterValue": "А - Я", "filterText": "А - Я"},
                                       {"filterId": "GenderFilter", "filterValue": "A", "filterText": "Все"},
                                       {"filterId": "work-status", "filterValue": "-1",
                                        "filterText": "Все сотрудники"}]},
                "fields": ["fio", "gender", "staffPosition", "staffRoles"],
                "search": {"fieldId": "lastName", "fieldTitle": "Фамилия", "text": "",
                           "fields": [{"id": "fio", "title": "Ф.И.О.",
                                       "sortable": True, "order": 1, "default": True, "search": True,
                                       "searchByDefault": False, "grouped": False,
                                       "decorator": {"type": "link"}},
                                      {"id": "lastName", "title": "Фамилия", "sortable": True, "order": 2,
                                       "default": False,
                                       "search": True, "searchByDefault": True, "grouped": False},
                                      {"id": "staffPosition", "title": "Основная должность", "sortable": True,
                                       "order": 6, "default": True, "search": True, "searchByDefault": False,
                                       "grouped": False},
                                      {"id": "loginName", "title": "Логин", "sortable": True, "order": 200,
                                       "default": False, "search": True, "searchByDefault": False, "grouped": False}]},
                "order": None, "page": None, "pageSize": None}
